version: "3.7"

services:
  app:
    build: .
    container_name: github-proxy
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app